.TH IQ-CLI "1" "June 2016" "iqcash-cli 0.12"
.SH NAME
iqcash-cli \- a remote procedure call client for IQcash Core. 
.SH SYNOPSIS
iqcash-cli [options] <command> [params] \- Send command to IQcash Core. 
.TP
iqcash-cli [options] help \- Asks IQcash Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the iqcash-cli program. iqcash-cli is an RPC client used to send commands to IQcash Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBiqcashd\fP, \fBiqcash.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
